//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace tareafinal.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class bancoEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto bancoEntities usando la cadena de conexión encontrada en la sección 'bancoEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public bancoEntities() : base("name=bancoEntities", "bancoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto bancoEntities.
        /// </summary>
        public bancoEntities(string connectionString) : base(connectionString, "bancoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto bancoEntities.
        /// </summary>
        public bancoEntities(EntityConnection connection) : base(connection, "bancoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cliente> clientes
        {
            get
            {
                if ((_clientes == null))
                {
                    _clientes = base.CreateObjectSet<cliente>("clientes");
                }
                return _clientes;
            }
        }
        private ObjectSet<cliente> _clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ejecutivo> ejecutivoes
        {
            get
            {
                if ((_ejecutivoes == null))
                {
                    _ejecutivoes = base.CreateObjectSet<ejecutivo>("ejecutivoes");
                }
                return _ejecutivoes;
            }
        }
        private ObjectSet<ejecutivo> _ejecutivoes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sucursal> sucursals
        {
            get
            {
                if ((_sucursals == null))
                {
                    _sucursals = base.CreateObjectSet<sucursal>("sucursals");
                }
                return _sucursals;
            }
        }
        private ObjectSet<sucursal> _sucursals;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<targeta> targetas
        {
            get
            {
                if ((_targetas == null))
                {
                    _targetas = base.CreateObjectSet<targeta>("targetas");
                }
                return _targetas;
            }
        }
        private ObjectSet<targeta> _targetas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<transaccion> transaccions
        {
            get
            {
                if ((_transaccions == null))
                {
                    _transaccions = base.CreateObjectSet<transaccion>("transaccions");
                }
                return _transaccions;
            }
        }
        private ObjectSet<transaccion> _transaccions;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToclientes(cliente cliente)
        {
            base.AddObject("clientes", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ejecutivoes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToejecutivoes(ejecutivo ejecutivo)
        {
            base.AddObject("ejecutivoes", ejecutivo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sucursals. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosucursals(sucursal sucursal)
        {
            base.AddObject("sucursals", sucursal);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet targetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotargetas(targeta targeta)
        {
            base.AddObject("targetas", targeta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet transaccions. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotransaccions(transaccion transaccion)
        {
            base.AddObject("transaccions", transaccion);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bancoModel", Name="cliente")]
    [Serializable()]

    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cliente.
        /// </summary>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        public static cliente Createcliente(global::System.Int32 id_cliente)
        {
            cliente cliente = new cliente();
            cliente.id_cliente = id_cliente;
            return cliente;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                if (_id_cliente != value)
                {
                    Onid_clienteChanging(value);
                    ReportPropertyChanging("id_cliente");
                    _id_cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cliente");
                    Onid_clienteChanged();
                }
            }
        }
        private global::System.Int32 _id_cliente;
        partial void Onid_clienteChanging(global::System.Int32 value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bancoModel", Name="ejecutivo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ejecutivo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ejecutivo.
        /// </summary>
        /// <param name="id_ejecutivo">Valor inicial de la propiedad id_ejecutivo.</param>
        public static ejecutivo Createejecutivo(global::System.Int32 id_ejecutivo)
        {
            ejecutivo ejecutivo = new ejecutivo();
            ejecutivo.id_ejecutivo = id_ejecutivo;
            return ejecutivo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_ejecutivo
        {
            get
            {
                return _id_ejecutivo;
            }
            set
            {
                if (_id_ejecutivo != value)
                {
                    Onid_ejecutivoChanging(value);
                    ReportPropertyChanging("id_ejecutivo");
                    _id_ejecutivo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_ejecutivo");
                    Onid_ejecutivoChanged();
                }
            }
        }
        private global::System.Int32 _id_ejecutivo;
        partial void Onid_ejecutivoChanging(global::System.Int32 value);
        partial void Onid_ejecutivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sucursal
        {
            get
            {
                return _sucursal;
            }
            set
            {
                OnsucursalChanging(value);
                ReportPropertyChanging("sucursal");
                _sucursal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sucursal");
                OnsucursalChanged();
            }
        }
        private Nullable<global::System.Int32> _sucursal;
        partial void OnsucursalChanging(Nullable<global::System.Int32> value);
        partial void OnsucursalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String contrasena
        {
            get
            {
                return _contrasena;
            }
            set
            {
                OncontrasenaChanging(value);
                ReportPropertyChanging("contrasena");
                _contrasena = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contrasena");
                OncontrasenaChanged();
            }
        }
        private global::System.String _contrasena;
        partial void OncontrasenaChanging(global::System.String value);
        partial void OncontrasenaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String rut
        {
            get
            {
                return _rut;
            }
            set
            {
                OnrutChanging(value);
                ReportPropertyChanging("rut");
                _rut = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rut");
                OnrutChanged();
            }
        }
        private global::System.String _rut;
        partial void OnrutChanging(global::System.String value);
        partial void OnrutChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bancoModel", Name="sucursal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sucursal : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sucursal.
        /// </summary>
        /// <param name="id_sucursal">Valor inicial de la propiedad id_sucursal.</param>
        public static sucursal Createsucursal(global::System.Int32 id_sucursal)
        {
            sucursal sucursal = new sucursal();
            sucursal.id_sucursal = id_sucursal;
            return sucursal;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_sucursal
        {
            get
            {
                return _id_sucursal;
            }
            set
            {
                if (_id_sucursal != value)
                {
                    Onid_sucursalChanging(value);
                    ReportPropertyChanging("id_sucursal");
                    _id_sucursal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_sucursal");
                    Onid_sucursalChanged();
                }
            }
        }
        private global::System.Int32 _id_sucursal;
        partial void Onid_sucursalChanging(global::System.Int32 value);
        partial void Onid_sucursalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bancoModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagram.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bancoModel", Name="targeta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class targeta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto targeta.
        /// </summary>
        /// <param name="id_targeta">Valor inicial de la propiedad id_targeta.</param>
        public static targeta Createtargeta(global::System.Int32 id_targeta)
        {
            targeta targeta = new targeta();
            targeta.id_targeta = id_targeta;
            return targeta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_targeta
        {
            get
            {
                return _id_targeta;
            }
            set
            {
                if (_id_targeta != value)
                {
                    Onid_targetaChanging(value);
                    ReportPropertyChanging("id_targeta");
                    _id_targeta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_targeta");
                    Onid_targetaChanged();
                }
            }
        }
        private global::System.Int32 _id_targeta;
        partial void Onid_targetaChanging(global::System.Int32 value);
        partial void Onid_targetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cliente
        {
            get
            {
                return _cliente;
            }
            set
            {
                OnclienteChanging(value);
                ReportPropertyChanging("cliente");
                _cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cliente");
                OnclienteChanged();
            }
        }
        private Nullable<global::System.Int32> _cliente;
        partial void OnclienteChanging(Nullable<global::System.Int32> value);
        partial void OnclienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> vencimiento
        {
            get
            {
                return _vencimiento;
            }
            set
            {
                OnvencimientoChanging(value);
                ReportPropertyChanging("vencimiento");
                _vencimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vencimiento");
                OnvencimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _vencimiento;
        partial void OnvencimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnvencimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> limite
        {
            get
            {
                return _limite;
            }
            set
            {
                OnlimiteChanging(value);
                ReportPropertyChanging("limite");
                _limite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("limite");
                OnlimiteChanged();
            }
        }
        private Nullable<global::System.Int64> _limite;
        partial void OnlimiteChanging(Nullable<global::System.Int64> value);
        partial void OnlimiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bancoModel", Name="transaccion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class transaccion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto transaccion.
        /// </summary>
        /// <param name="id_transaccion">Valor inicial de la propiedad id_transaccion.</param>
        public static transaccion Createtransaccion(global::System.Int32 id_transaccion)
        {
            transaccion transaccion = new transaccion();
            transaccion.id_transaccion = id_transaccion;
            return transaccion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_transaccion
        {
            get
            {
                return _id_transaccion;
            }
            set
            {
                if (_id_transaccion != value)
                {
                    Onid_transaccionChanging(value);
                    ReportPropertyChanging("id_transaccion");
                    _id_transaccion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_transaccion");
                    Onid_transaccionChanged();
                }
            }
        }
        private global::System.Int32 _id_transaccion;
        partial void Onid_transaccionChanging(global::System.Int32 value);
        partial void Onid_transaccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ejecutivo
        {
            get
            {
                return _ejecutivo;
            }
            set
            {
                OnejecutivoChanging(value);
                ReportPropertyChanging("ejecutivo");
                _ejecutivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ejecutivo");
                OnejecutivoChanged();
            }
        }
        private Nullable<global::System.Int32> _ejecutivo;
        partial void OnejecutivoChanging(Nullable<global::System.Int32> value);
        partial void OnejecutivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numerotargeta
        {
            get
            {
                return _numerotargeta;
            }
            set
            {
                OnnumerotargetaChanging(value);
                ReportPropertyChanging("numerotargeta");
                _numerotargeta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numerotargeta");
                OnnumerotargetaChanged();
            }
        }
        private Nullable<global::System.Int32> _numerotargeta;
        partial void OnnumerotargetaChanging(Nullable<global::System.Int32> value);
        partial void OnnumerotargetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha;
        partial void OnfechaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> monto
        {
            get
            {
                return _monto;
            }
            set
            {
                OnmontoChanging(value);
                ReportPropertyChanging("monto");
                _monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("monto");
                OnmontoChanged();
            }
        }
        private Nullable<global::System.Int32> _monto;
        partial void OnmontoChanging(Nullable<global::System.Int32> value);
        partial void OnmontoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String saldo
        {
            get
            {
                return _saldo;
            }
            set
            {
                OnsaldoChanging(value);
                ReportPropertyChanging("saldo");
                _saldo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("saldo");
                OnsaldoChanged();
            }
        }
        private global::System.String _saldo;
        partial void OnsaldoChanging(global::System.String value);
        partial void OnsaldoChanged();

        #endregion

    
    }

    #endregion

    
}
